<table align="center" width=100%>
    <tr>
       <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> MINI PROJECT 1<br>
                    </b>
                </font>
            </div>
        </td>
        <td width="25%">
            <img src="NEW_GL_Logo.png">
        </td>
    </tr>
</table>


## Group Members Name
  
<div class="alert alert-warning">
<p style="font-family: Arial Black; font-size:1.4em;color:Purple;">  
1.  G. R. Priyavarshini
<div class="alert alert-warning">
<p style="font-family: Arial Black; font-size:1.4em;color:Purple;">    
2.  G. R. Tamothar
<div class="alert alert-warning">
<p style="font-family: Arial Black; font-size:1.4em;color:Purple;">    
3.  T. Uma Maheshwari

## 1. Write a program to transpose a matrix (3 marks)   matrix= [[1,2,3],[3,4,5],[5,6,8],[7,8,9]]

#### METHOD 1 : TRADITIONAL WAY OF PYTHON CODING

In [1]:
#we initialize a matrix
matrix = [[1, 2, 3], [3, 4, 5], [5, 6, 8], [7, 8, 9]]
#initialize transpose with size of matrix transpose
transpose = [[0 for j in range(len(matrix))] for i in range(len(matrix[0]))]
#transpose into 3*4 matrix
#transpose = [[0,0,0,0],[0,0,0,0],[0,0,0,0]]
#The above can also be used initialize transpose with size of matrix transpose
#now we apply the loop
for i in range(len(matrix)):
    # iterate through columns
    for j in range(len(matrix[0])):
        transpose[j][i] = matrix[i][j]
print(transpose)

[[1, 3, 5, 7], [2, 4, 6, 8], [3, 5, 8, 9]]


#### Summary: 
<div class="alert alert-danger"><p style="font-family: Times New Roman; font-size:1.4em;color:Purple;">The matrix transpose is done using nested loop. We are creating a matrix and then creating another matrix of the same size as the original matrix to store the results back after transpose. We do not do a hard code of the results matrix because we do not know the dimension of the matrix in the future. So, we are creating the result matrix size using the original matrix size itself. We use some pythonic ways to find out the dimension of the transpose matrix using the original matrix. Because if we do not do this, then we have to mention the dimension of the transpose matrix. But with this method, we do not care about the dimensions of the matrix. We run two loops. One upper loop is for the rows and the nested loop for the column-wise. We are printing the transpose matrix (transpose),and from the results, we found that our matrix is now transposed. 

#### METHOD 2 : USING zip() FUNCTION

In [2]:
X = [1,2,3], [3, 4, 5], [5, 6, 8], [7, 8, 9]
zip(*X)
[list(tup) for tup in zip(*X)]

[[1, 3, 5, 7], [2, 4, 6, 8], [3, 5, 8, 9]]

#### Summary: 

<div class="alert alert-warning">
<p style="font-family: Times New Roman; font-size:1.4em;color:brown;">
*  (*) is the unpacking syntax
<div class="alert alert-warning">
<p style="font-family: Times New Roman; font-size:1.4em;color:brown;">
*  zip(*X)---->zip([1,2,3], [3, 4, 5], [5, 6, 8], [7, 8, 9])
<div class="alert alert-warning">
<p style="font-family:Times New Roman; font-size:1.4em;color:brown;">
   The zip() function returns a zip object, which is an iterator of tuples where the first item 
   in each passed iterator is paired together, and then the second item in each passed iterator are paired together etc.
<div class="alert alert-warning">   
<p style="font-family: Times New Roman; font-size:1.4em;color:brown;">   
*  zip([1,2,3], [3, 4, 5], [5, 6, 8], [7, 8, 9])----> returns as tuple ---->[(1, 3, 5, 7), (2, 4, 6, 8), (3, 5, 8, 9)]
<div class="alert alert-warning">
<p style="font-family:Times New Roman; font-size:1.4em;color:brown;">
*  If the inner pairs absolutely need to be lists
   [list(tup) for tup in zip(*X)]</div>


#### METHOD 3: USING numpy

In [3]:
import numpy as np
arr1 = [[1, 2, 3], [3, 4, 5], [5, 6, 8], [7, 8, 9]] 
#The transpose() function works with an array like object too, such as a nested list.
arr1_transpose = np.transpose(arr1)
print(arr1_transpose)

[[1 3 5 7]
 [2 4 6 8]
 [3 5 8 9]]


#### Summary:
<div class="alert alert-success">
<p style="font-family: Times New Roman; font-size:1.4em;color:Magenta;"> 
If we are working with matrices, you should almost certainly be using numpy. This will perform numerical operations easier and more efficiently than pure Python code.

### 2. Create a dictionary containing four lambda functions square, cube, squareroot, multiply by 3 (8 marks)

**E.g. dict = {'Square': function for squaring, 'Cube': function for cube, 'Squareroot': function for squareroot, 'Double': function for double} and so on**

**Pass the values (input from the user) to the functions in the dictionary respectively. Then add the outputs of each function and print it.**

In [4]:
# we create the function
def addFunc(number):
    
    # we create dictionary containing four lambda functions 
    MathFunc = {
        'Square': lambda a: a**2, #lambda parameter:expression
        'Cube': lambda a: a**3,
        'Squareroot': lambda a: a**0.5,
        'Multiply by 3': lambda a: a * 3 #if the input =6: square=36,cube=216,squareroot=2.44,triple=18
    }
    
    # to store the ouputs we create and initialise with 0
    final = 0
    # iterate through keys
    for key in MathFunc.keys():
        final += MathFunc[key](number) #if the input =6: square+cube+squareroot+triple =272.44
    return final

addFunc(int(input()))

6


272.44948974278316

<strong>Summary: </strong> 
<div class="alert alert-danger"> 
<p style="font-family: Times New Roman; font-size:1.4em;color:gold;"><span style='color:Orange'> 
First step ---> Create function called addFunc 
<p style="font-family:Times New Roman; font-size:1.4em;color:gold;"><span style='color:Orange'> 
Second step ---> Create a dictionary containing four lambda functions
<p style="font-family: Times New Roman; font-size:1.4em;color:gold;"><span style='color:Orange'> 
Third step ---> To store the ouputs we create and initialise with 0
<p style="font-family: Times New Roman; font-size:1.4em;color:gold;"><span style='color:Orange'> 
Fourth step ---> Iterate through keys
<p style="font-family: Times New Roman; font-size:1.4em;color:gold;"><span style='color:Orange'> 
Fifth step ---> Calling the function by passing a argument using runtime variable
<p style="font-family: Times New Roman; font-size:1.4em;color:gold;"><span style='color:Orange'> 
If the input =6: square+cube+squareroot+triple =272.44

</span>  
    

###  3. A list of words is given. Define a function to find the words from the list that have their second character in uppercase (4 marks)

<b>list1 = ['swiggy', 'Zomato', 'aMazon', 'TATa Cliq', 'uBer', 'JioMart','BIG BASKET' ]</b><br>

In [5]:
# we create the function
def find2ndUpprChr(words):
    
    # iterate list find the upper character of 2nd element of each value
    return [item for item in words if item[1].isupper()]
    
#Declaraing the list
list1 = ['swiggy', 'Zomato', 'aMazon', 'TATa Cliq', 'uBer', 'JioMart','BIG BASKET']

# call the function
find2ndUpprChr(list1)

['aMazon', 'TATa Cliq', 'uBer', 'BIG BASKET']

<strong>Summary: </strong> 
<div class="alert alert-warning">    
<p style="font-family: Times New Roman; font-size:1.4em;color:lime;">    
First step ---> Create the function as find2ndUpprChr
<div class="alert alert-warning">
<p style="font-family: Times New Roman; font-size:1.4em;color:lime;"> 
Second step ---> Iterate list
<div class="alert alert-warning">
<p style="font-family: Times New Roman; font-size:1.4em;color:lime;"> 
Third step ---> find the upper character of 2nd element of each value using isupper()
<div class="alert alert-warning">
<p style="font-family: Times New Roman; font-size:1.4em;color:lime;"> 
Fourth step ---> Declaraing the list
<div class="alert alert-warning">
<p style="font-family: Times New Roman; font-size:1.4em;color:lime;"> 
Fifth step ---> Calling the function
    

 ### 4. Define a function to filter the marks from the tuple "tmarks" that are greater than 40 and print corresponding names from the "tnames" tuple (2 marks)

<b>tnames = ('John','Sharon','Jack','Annie', 'Antony', 'Thomson', 'Rijo')</b><br>
<b>tmarks = (32,50,75,12,40,23,37)</b>

In [6]:
def FilterMarks(tmarks, tnames): #Define a function named FilterMarks
    for mark in tmarks:
        index = tmarks.index(mark)
        if mark > 40:
            print(tnames[index],tmarks[index]) #using if condition to filter out tmarks greater than 40

tnames = ('John', 'Sharon', 'Jack', 'Annie', 'Antony', 'Thomson', 'Rijo')
tmarks = (32, 50, 75, 12, 40, 23, 37)

FilterMarks(tmarks, tnames)

Sharon 50
Jack 75


<strong>Summary: </strong> 
<div class="alert alert-info">    
<p style="font-family: Times New Roman; font-size:1.4em;color:DarkBlue;">  
First step ---> Define a function named FilterMarks
<div class="alert alert-info">    
<p style="font-family: Times New Roman; font-size:1.4em;color:DarkBlue;">  
Second step ---> Filtering the marks from the tuple "tmarks" by index
<div class="alert alert-info">    
<p style="font-family: Times New Roman; font-size:1.4em;color:DarkBlue;">  
Third step ---> using if condition to filter out tmarks greater than 40
<div class="alert alert-info">    
<p style="font-family: Times New Roman; font-size:1.4em;color:DarkBlue;">  
Fourth step ---> Printing the corresponding tnames to tmarks by passing it as argument to the calling function
    

### 5. A dictionary of names and their weights on earth is given. Find how much they will weight on the moon. (use map and lambda functions) (3 marks)

**Weight of people in kg**
WeightOnEarth = {'John':45, 'Shelly':65, 'Marry':35}        

**Gravitational force on the Moon**
GMoon = 1.622                                              

**Gravitational force on the Earth**
GEarth = 9.81                                              

**Output:** 
Weight on Moon:  {'John': 7.44, 'Shelly': 10.75, 'Marry': 5.79}

In [7]:
# Weight of people in kg
# Gravitational force on the Moon: 1.622 m/s2
# Gravitational force on the Earth: 9.81 m/s2
# Formula : wMoon = (wEarth * GMoon) / GEartZ
WeightOnEarth = {'John':45, 'Shelly':65, 'Marry':35}  
GMoon = 1.622
GEarth = 9.81
WMoon = lambda item: (item[0], round((item[1] * GMoon / GEarth), 2))
WeightonMoon = dict(map(WMoon,WeightOnEarth.items()))
print(f"Weight on Moon: {WeightonMoon}")

Weight on Moon: {'John': 7.44, 'Shelly': 10.75, 'Marry': 5.79}


<strong>Summary: </strong> 
<div class="alert alert-success">    
<p style="font-family: Times New Roman; font-size:1.4em;color:olive;">  
First step ---> Declaring variables
<div class="alert alert-success">    
<p style="font-family: Times New Roman; font-size:1.4em;color:olive;">  
Second step ---> Using lambda function for calculating weight on the moon
<div class="alert alert-success">    
<p style="font-family: Times New Roman; font-size:1.4em;color:olive;">  
Third step ---> map() function returns a map object(which is an iterator) of the results after applying the given 
function to each item of a given iterable (list, tuple etc.)
<div class="alert alert-success">    
<p style="font-family: Times New Roman; font-size:1.4em;color:olive;">  
Fourth step ---> Priting Weight on Moon